name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build with Vite
        run: npm run build
          
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Создаем бэкап текущей версии
            sudo cp -r /var/www/demo1.websmith-shop.com /var/www/demo1.websmith-shop.com.backup.$(date +%Y%m%d_%H%M%S) || true
            
            # Очищаем директорию
            sudo rm -rf /var/www/demo1.websmith-shop.com/*
            
            # Создаем временную директорию для загрузки
            sudo mkdir -p /tmp/demo1-deploy
            
      - name: Upload files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist/"
          target: "/tmp/demo1-deploy"
          strip_components: 0
          
      - name: Set permissions and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Перемещаем файлы из временной директории в основную
            sudo cp -r /tmp/demo1-deploy/* /var/www/demo1.websmith-shop.com/
            
            # Устанавливаем правильные права
            sudo chown -R www-data:www-data /var/www/demo1.websmith-shop.com
            sudo chmod -R 755 /var/www/demo1.websmith-shop.com
            
            # Очищаем временную директорию
            sudo rm -rf /tmp/demo1-deploy
            
            # Перезапускаем nginx
            sudo systemctl reload nginx
            sudo systemctl status nginx
